//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderDuckGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Td_BrandMaker_Images
    {
        public int id { get; set; }
        public string images1 { get; set; }
        public string Subtitle { get; set; }
        public string Title { get; set; }
    }
}
