//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderDuckGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Td_Constrution_Story
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Signature { get; set; }
        public string Images { get; set; }
        public string Description1 { get; set; }
    }
}
