//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderDuckGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Td_Construction_Slider
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Images { get; set; }
        public string Images1 { get; set; }
        public string Images2 { get; set; }
        public string Title1 { get; set; }
        public string Subtitle1 { get; set; }
        public string Title2 { get; set; }
        public string Subtitle2 { get; set; }
    }
}
