//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderDuckGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Td_Construction_Contact
    {
        public int id { get; set; }
        public string HeadAddress { get; set; }
        public string OfficeAddress { get; set; }
        public string Email { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Phone { get; set; }
        public string Phone1 { get; set; }
        public string Hotline { get; set; }
    }
}
